### ISSUE TITLE
tmp files must be deleted always

### ISSUE THREAD

**Issue by alfem** [gecos-team/gecosws-config-assistant#6]
Some credentials are stored in temporary files, and these are not always deleted.

These files must be deleted as soon as possible.

(Even better, they must be avoided, using memory files if possible)

**Comment by System25** [comment]
It seems that the temporary files can't be replaced by "in memory" files because they are neccessary to run a separate process with "chef-solo"

**Comment by alfem** [comment]
Well, let's use mktemp or pid to isolate logs from differents runs
