### ISSUE TITLE
Progress windows and bars are not useful

### ISSUE THREAD

**Issue by alfem** [gecos-team/gecosws-config-assistant#8]
GCA launch two separate windows with "progress bars".

The behaviour is not intuitive and information showed is really scarce.

**Comment by System25** [comment]
Maybe CGA must launch only one window with a "progress bar". Run the first configuration process, set the bar to 50%, run the second configuration process and set the bar to 100%.

What would be the behaviour if the first process fail? It would start the second configuration process or not?

Both configuration process runs: gem, chef-solo and chef-client-wrapper. Maybe we could display information about the current step inside the process.

**Comment by alfem** [comment]
An unique process windows will be fine, or two in sequence. I think this last option could be better if one of two processes fails and needs rollback. 

Both sections (CC config and Login Method config) are independent and optional. The use can config only one, both or none. If one of them fails, it must allow a retry. 

About the chef-client-wrapper, I think that is an unnecesary step. Or at least it must be optional, as it would be executed (theorically) in the next reboot. 
Some informative messages instead of a ping-pong bar would be useful too.

**Comment by juanconde** [comment]
In case chef-client is not launched from GCA, we still need to take care of running (scheduled) instances of chef-client, as those may conflict with chef-solo launched by GCA.

**Comment by System25** [comment]
Thinking about it, and maybe the two process dialog in sequence are fine. And to maximize the information providen to the user, I created a patch that adds a "label" that displays a message about the current stage of the process and a TextView that shows the "chef-solo" log.

![image](https://cloud.githubusercontent.com/assets/4385829/8498213/8b4b20a4-2184-11e5-84c9-46c449da9d39.png)

Please considerate it

**Comment by alfem** [comment]
I think it is ok.
