### ISSUE TITLE
Active Directory configuration does not allow to access shares or printers

### ISSUE THREAD

**Issue by alfem** [gecos-team/gecosws-config-assistant#9]
GCA connects a workstation to AD for user login, but shared folders and printers ask for credentials again when accesed. In a kerberised environment this must be avoided.

P.S.: if this bug must be solved in gecos-workstation-cookbook, just move it there

**Comment by hfiel** [comment]
This issue implies two parts:
- Shared folders
- Shared printers

I have created an issue related to the first part, https://github.com/gecos-team/gecos-workstation-management-cookbook/issues/136
